name: Build on master

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build for test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hello World
        run: |
          echo Hello github actions
